project:
  type: book

book:
  title: "Curriculum del Programa de Campeones de rOpenSci"
  author: "Yanina Bellini Saibene, Maëlle Salmon, Paola Corrales, Mauro Lepore, Alejandra Bellini, Noam Ross"
  date: "2026"
  repo-url: https://github.com/ropensci-training/curriculum
  repo-actions: [edit, issue]
  sharing: [linkedin]
  chapters:
    - index.es.qmd
    - intro.es.qmd
    - como-usar.es.qmd
    - como-contribuir.es.qmd
    - part: "Mentoría"
      chapters:
        - mentoring/mentors.es.qmd
        - mentoring/mentors-schedule.es.qmd
        - mentoring/mentors-materials.es.qmd
        - mentoring/mentors-instructor-notes.es.qmd
    - part: "Desarrollo colaborativo de software"
      chapters:
        - git/software-community-intro.es.qmd
        - git/software-community-preparation.es.qmd
        - git/software-community-git-individual.es.qmd
        - git/software-community-git-team.es.qmd
        - git/software-community-git-instructor-notes.es.qmd
        - git/git-history.es.qmd
        - git/git-history-instructor-notes.es.qmd
        - git/git-advanced.es.qmd
        - git/git-advanced-instructor-notes.es.qmd
    - part: "Desarrollo de paquetes de R"
      chapters:
        - packages/code-quality.es.qmd
        - packages/code-quality-instructor-notes.es.qmd
        - packages/mechanics-prereqs.es.qmd
        - packages/mechanics-1.es.qmd
        - packages/mechanics-1-instructor-notes.es.qmd
        - packages/mechanics-2.es.qmd
        - packages/mechanics-2-instructor-notes.es.qmd
        - packages/mechanics-3.es.qmd
        - packages/mechanics-3-instructor-notes.es.qmd
        - packages/advanced.es.qmd
        - packages/advanced-instructor-notes.es.qmd
        - packages/packages-genia.es.qmd
        - packages/packages-genie-instructor-notes.es.qmd
    - part: "Revisión de software"
      chapters:
        - review/review-process.es.qmd
        - review/review-process-instructor-notes.es.qmd
        - review/review-workshop.es.qmd
        - review/review-workshop-instructor-notes.es.qmd
    - part: "Gestión de comunidad y divulgación"
      chapters:
        - community/oss-contribution.es.qmd
        - community/oss-contribution-instructor-notes.es.qmd
        - community/memorable-talk.es.qmd
        - community/memorable-talk-tools.es.qmd
        - community/memorable-talk-instructor-notes.es.qmd
        - community/wonderful-event.es.qmd
        - community/wonderful-event-instructor-notes.es.qmd
  #   - part: "Apéndices"
  #     chapters:
  #       - apendices/apendice-glosario.es.qmd
  #       - apendices/apendice-entorno.es.qmd
  #       - apendices/apendice-plantilla-instructor.es.qmd
  # appendices:
  #   - references.es.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    lang: es
  pdf:
    documentclass: book
    lang: es

babelquarto:
  languagecodes:
    - name: es
      text: "Español"
    - name: en
      text: "English"
    - name: pt
      text: "Português"
  mainlanguage: "es"
  languages: ["en", "pt"]
