project:
  type: book

book:
  title: "Curriculum del Programa de Campeon(a|e)s de rOpenSci"
  author: "Yanina Bellini Saibene, Maëlle Salmon, Paola Corrales, Mauro Lepore, Alejandra Bellini, Noam Ross, Elio Campitelli"
  date: "2026"
  repo-url: https://github.com/ropensci-training/curriculum
  repo-actions: [edit, issue]
  sharing: [linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - how-to-use.qmd
    - contributing.qmd
    - part: "Mentoría"
      chapters:
        - mentoring/mentors.qmd
        - mentoring/mentors-schedule.qmd
        - mentoring/mentors-materials.qmd
        - mentoring/mentors-instructor-notes.qmd
    - part: "Desarrollo colaborativo de software"
      chapters:
        - git/software-community-intro.qmd
        - git/software-community-preparation.qmd
        - git/software-community-git-individual.qmd
        - git/software-community-git-team.qmd
        - git/software-community-git-instructor-notes.qmd
        - git/git-history.qmd
        - git/git-history-instructor-notes.qmd
        - git/git-advanced.qmd
        - git/git-advanced-instructor-notes.qmd
    - part: "Desarrollo de paquetes de R"
      chapters:
        - packages/code-quality.qmd
        - packages/code-quality-instructor-notes.qmd
        - packages/mechanics-prereqs.qmd
        - packages/mechanics-1.qmd
        - packages/mechanics-1-instructor-notes.qmd
        - packages/mechanics-2.qmd
        - packages/mechanics-2-instructor-notes.qmd
        - packages/mechanics-3.qmd
        - packages/mechanics-3-instructor-notes.qmd
        - packages/advanced.qmd
        - packages/advanced-instructor-notes.qmd
        - packages/packages-genai.qmd
        - packages/packages-genai-instructor-notes.qmd
    - part: "Revisión de software"
      chapters:
        - review/review-process.qmd
        - review/review-process-instructor-notes.qmd
        - review/review-workshop.qmd
        - review/review-workshop-instructor-notes.qmd
    - part: "Gestión de comunidad y divulgación"
      chapters:
        - community/oss-contribution.qmd
        - community/oss-contribution-instructor-notes.qmd
        - community/memorable-talk.qmd
        - community/memorable-talk-tools.qmd
        - community/memorable-talk-instructor-notes.qmd
        - community/wonderful-event.qmd
        - community/wonderful-event-instructor-notes.qmd
  #   - part: "Appendices"
  #     chapters:
  #       - appendix/apendice-glosario.es.qmd
  #       - appendix/apendice-entorno.es.qmd
  #       - appendix/apendice-plantilla-instructor.es.qmd
  # appendices:
  #   - references.es.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    lang: es
  # pdf:
  #   documentclass: book
  #   lang: es

babelquarto:
  languagecodes:
    - name: es
      text: "Español"
    - name: en
      text: "English"
    - name: pt
      text: "Português"
  mainlanguage: "es"
  languages: ["en", "pt"]
