---
title: "Desarrollo de paquetes para principiantes: la mecánica"
---

::: {.callout-note}
## Migración

Estás leyendo la **primera edición en progreso y en castellano** de este libro, basada en el currículum de formación del programa de Campones/as de rOpenSci.

Este capítulo está siendo migrado desde los materiales del currículum al formato del libro y puede no reflejar todavía la versión final del contenido.

*Fuente del contenido:* ver https://github.com/ropensci-training/2026-pkg-dev-mechanics para el repo fuente de este capítulo. Hay mas repos pero esta es la version mas actualizada.
:::

## De que va este curso

¿Qué significa desarrollar un paquete R?
En esta sesión con una demostración en vivo, desmitificaremos la creación de un paquete R.
Los paquetes R son, en su mayoría, carpetas bien organizadas, y existen herramientas automáticas que ayudan a crearlos. 
¡Descubre las maravillas de usethis!

## Preparación antes de la primera sesión

Antes de empezar a escribir paquetes...

- Configurá tu sistema como está [explicado en el libro Paquetes R de Hadley Wickham y Jenny Bryan](https://r-pkgs.org/setup.html). Ponéte en contacto conmigo (mensaje de Slack o email) si cuando llamás a la función `devtools::has_devel()` te da un error que te desconcierta.

- Si querés, instala [Positron](https://positron.posit.co/download.html). Es lo que usaré para las demos, pero si preferís podés usar RStudio IDE, o cualquier otra IDE.

- [Creá una cuenta GitHub](https://happygitwithr.com/github-acct), [instala Git](https://happygitwithr.com/install-git). Tené en cuenta que ya deberías tener estas herramientas listas si hicistes los talleres de Git y GitHub.

- Conectá también R con tu cuenta de GitHub. Consultá [Gestión de credenciales Git(Hub)](https://usethis.r-lib.org/articles/git-credentials.html) (y [Gestión de credenciales GitHub desde R, nivel de dificultad linux](https://blog.djnavarro.net/posts/2021-08-08_git-credential-helpers/) si es necesario :sweat_smile:). Ponéte en contacto conmigo (mensaje de Slack o email) si cuando llamás a la función `usethis::git git_sitrep()` te da un error que te desconcierta.

- Aprendé a escribir funciones. Algunos enlaces útiles (en Inglés):
  
  - [Escribí tus propias funciones en R](https://stat545.com/functions-part1.html), curso stat 545 por Jenny Bryan y The STAT 545 TAs;
  - [Capítulo sobre funciones](https://r4ds.had.co.nz/functions.html) en el libro "R for Data Science" de Garrett Grolemund y Hadley Wickham;
  - [Charla "Fun with Functions](https://www.kaylea.co.uk/talk/funwithfunctions/) por Kaylea Haynes, R-Ladies Manchester.
  - [Materiales del tutorial de Stephanie Kirmer](https://github.com/rladies-eastlansing/2021-rfunctions#writing-r-functions)

- Aprendé a escribir funciones. Algunos enlaces útiles (en Español):
  - [Introducción a la Programación II](https://intro-programacion.netlify.app/07_funciones), curso por Paola Corrales y Yanina Bellini Saibene.

- **¡Prepará tus preguntas!**
    




